// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApi.Data;

namespace MoviesAPI.Data.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20190323222928_InitialMigrationAndDataSeed")]
    partial class InitialMigrationAndDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesApi.Data.Entities.MovieEntity", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("RunningTime");

                    b.Property<string>("Title");

                    b.Property<int>("YearOfRelease");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63350e4a-a5fb-42bd-83da-f75f7b8807b4"),
                            Genre = 8194,
                            RunningTime = 200,
                            Title = "Titanic",
                            YearOfRelease = 2000
                        },
                        new
                        {
                            Id = new Guid("61adc654-6f05-4aee-914e-6c7701e6ec76"),
                            Genre = 4,
                            RunningTime = 120,
                            Title = "Die Hard",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = new Guid("1abaadad-a1ee-403d-a17f-31321ec5859f"),
                            Genre = 32,
                            RunningTime = 631,
                            Title = "The Lord of the Rings",
                            YearOfRelease = 2007
                        },
                        new
                        {
                            Id = new Guid("560c0dbe-6927-41a1-8d8d-0789c4c9851d"),
                            Genre = 17,
                            RunningTime = 110,
                            Title = "Get Out",
                            YearOfRelease = 2018
                        },
                        new
                        {
                            Id = new Guid("ead5e981-2125-47a6-a0a6-b4d6ffa14339"),
                            Genre = 129,
                            RunningTime = 98,
                            Title = "27 Dresses",
                            YearOfRelease = 2011
                        },
                        new
                        {
                            Id = new Guid("b839d79d-a339-416d-ade0-936edbcf6691"),
                            Genre = 8192,
                            RunningTime = 127,
                            Title = "The Dutchess",
                            YearOfRelease = 2006
                        },
                        new
                        {
                            Id = new Guid("ca2a8812-e099-495f-b036-06accb4355a7"),
                            Genre = 12,
                            RunningTime = 163,
                            Title = "Casino Royale",
                            YearOfRelease = 2004
                        },
                        new
                        {
                            Id = new Guid("37498bd4-d693-4ce0-933c-6cc8f9377ae9"),
                            Genre = 1025,
                            RunningTime = 93,
                            Title = "The Simpsons Movie",
                            YearOfRelease = 2009
                        },
                        new
                        {
                            Id = new Guid("dc6b3d4d-959b-4cef-a7eb-f92731811b95"),
                            Genre = 5,
                            RunningTime = 118,
                            Title = "Iron Man",
                            YearOfRelease = 2007
                        },
                        new
                        {
                            Id = new Guid("81aa0a92-70fb-4ffc-860b-a81ca47be098"),
                            Genre = 5,
                            RunningTime = 145,
                            Title = "Iron Man 2",
                            YearOfRelease = 2010
                        },
                        new
                        {
                            Id = new Guid("f7b47d60-3232-426d-a1aa-833aef7bb676"),
                            Genre = 5,
                            RunningTime = 123,
                            Title = "Iron Man 3",
                            YearOfRelease = 2013
                        },
                        new
                        {
                            Id = new Guid("ab7be0f3-e394-4c98-a80c-8a94ba62bf2f"),
                            Genre = 6,
                            RunningTime = 120,
                            Title = "Batman",
                            YearOfRelease = 1989
                        },
                        new
                        {
                            Id = new Guid("49f63645-60ed-4651-9ed8-51536f553981"),
                            Genre = 16,
                            RunningTime = 111,
                            Title = "Saw",
                            YearOfRelease = 2003
                        },
                        new
                        {
                            Id = new Guid("2e3dc0d2-b37c-490e-912c-b8b150b716ac"),
                            Genre = 2048,
                            RunningTime = 87,
                            Title = "Man on Wire",
                            YearOfRelease = 2010
                        });
                });

            modelBuilder.Entity("MoviesApi.Data.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTimeOffset>("DateSet");

                    b.Property<Guid>("MovieId");

                    b.Property<decimal>("Rating");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e1529d-e2f9-45d6-8e86-4d404908ec1c"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 481, DateTimeKind.Unspecified).AddTicks(8747), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("63350e4a-a5fb-42bd-83da-f75f7b8807b4"),
                            Rating = 5m,
                            UserId = new Guid("8d61bd5e-d9b3-4eda-822c-d7ce257abbc2")
                        },
                        new
                        {
                            Id = new Guid("e8c18505-134f-4e49-8b3a-4748ca9dde7e"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(92), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("61adc654-6f05-4aee-914e-6c7701e6ec76"),
                            Rating = 9m,
                            UserId = new Guid("8d61bd5e-d9b3-4eda-822c-d7ce257abbc2")
                        },
                        new
                        {
                            Id = new Guid("1de965cc-af7d-434e-b999-2ce6273b4d89"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(106), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("1abaadad-a1ee-403d-a17f-31321ec5859f"),
                            Rating = 5.5m,
                            UserId = new Guid("8d61bd5e-d9b3-4eda-822c-d7ce257abbc2")
                        },
                        new
                        {
                            Id = new Guid("40b1fca2-4b54-495f-97f8-0706035766fd"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(106), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("560c0dbe-6927-41a1-8d8d-0789c4c9851d"),
                            Rating = 2.5m,
                            UserId = new Guid("8d61bd5e-d9b3-4eda-822c-d7ce257abbc2")
                        },
                        new
                        {
                            Id = new Guid("eadb0134-9b07-4e18-9402-dd5d99a4684b"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(111), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("ead5e981-2125-47a6-a0a6-b4d6ffa14339"),
                            Rating = 8m,
                            UserId = new Guid("8d61bd5e-d9b3-4eda-822c-d7ce257abbc2")
                        },
                        new
                        {
                            Id = new Guid("73b1143f-836b-4967-8696-f85f93a456c6"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(125), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("b839d79d-a339-416d-ade0-936edbcf6691"),
                            Rating = 1m,
                            UserId = new Guid("86e4da8a-6ea9-416a-af9b-c037249c8f3c")
                        },
                        new
                        {
                            Id = new Guid("0f4b7501-38c8-458f-ad04-79555c9acd47"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(129), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("ca2a8812-e099-495f-b036-06accb4355a7"),
                            Rating = 6m,
                            UserId = new Guid("86e4da8a-6ea9-416a-af9b-c037249c8f3c")
                        },
                        new
                        {
                            Id = new Guid("ca9e082e-445a-4c78-8df6-1d34487f7b5a"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(129), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("37498bd4-d693-4ce0-933c-6cc8f9377ae9"),
                            Rating = 3m,
                            UserId = new Guid("86e4da8a-6ea9-416a-af9b-c037249c8f3c")
                        },
                        new
                        {
                            Id = new Guid("4cbd91fe-ae0f-4013-9eb8-cd5a760b0011"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(134), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("dc6b3d4d-959b-4cef-a7eb-f92731811b95"),
                            Rating = 9m,
                            UserId = new Guid("86e4da8a-6ea9-416a-af9b-c037249c8f3c")
                        },
                        new
                        {
                            Id = new Guid("2dbe0a99-9918-45f0-b154-6f51ed7777a9"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(134), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("81aa0a92-70fb-4ffc-860b-a81ca47be098"),
                            Rating = 5.5m,
                            UserId = new Guid("86e4da8a-6ea9-416a-af9b-c037249c8f3c")
                        },
                        new
                        {
                            Id = new Guid("79b9cac7-29de-4af0-9216-216d7943a447"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(138), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("f7b47d60-3232-426d-a1aa-833aef7bb676"),
                            Rating = 8.5m,
                            UserId = new Guid("b18a8a2d-0369-48a4-8ca8-8af187487594")
                        },
                        new
                        {
                            Id = new Guid("237a56aa-6657-40bc-884f-d8388a4467b8"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(138), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("ab7be0f3-e394-4c98-a80c-8a94ba62bf2f"),
                            Rating = 6m,
                            UserId = new Guid("b18a8a2d-0369-48a4-8ca8-8af187487594")
                        },
                        new
                        {
                            Id = new Guid("8bb47064-2bf7-4f2a-9c21-1f529698f182"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(143), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("49f63645-60ed-4651-9ed8-51536f553981"),
                            Rating = 7m,
                            UserId = new Guid("b18a8a2d-0369-48a4-8ca8-8af187487594")
                        },
                        new
                        {
                            Id = new Guid("9052b80e-712d-4c8b-b3da-cfac0041cf1e"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(171), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("2e3dc0d2-b37c-490e-912c-b8b150b716ac"),
                            Rating = 8m,
                            UserId = new Guid("b18a8a2d-0369-48a4-8ca8-8af187487594")
                        },
                        new
                        {
                            Id = new Guid("625d2f78-50ac-4d41-bfaf-790a444add7c"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(171), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("63350e4a-a5fb-42bd-83da-f75f7b8807b4"),
                            Rating = 9m,
                            UserId = new Guid("b18a8a2d-0369-48a4-8ca8-8af187487594")
                        },
                        new
                        {
                            Id = new Guid("472edd2e-c60b-4ae8-9a34-cb8c8ade64eb"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(176), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("61adc654-6f05-4aee-914e-6c7701e6ec76"),
                            Rating = 10m,
                            UserId = new Guid("022b41a2-7e40-4104-98a9-7cd8dcc67a0f")
                        },
                        new
                        {
                            Id = new Guid("f902ae8e-0ca2-49c3-8f95-8a79fb581c11"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(176), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("1abaadad-a1ee-403d-a17f-31321ec5859f"),
                            Rating = 2m,
                            UserId = new Guid("022b41a2-7e40-4104-98a9-7cd8dcc67a0f")
                        },
                        new
                        {
                            Id = new Guid("da3af618-d1f0-4840-b3cb-87dd5a239cf7"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("560c0dbe-6927-41a1-8d8d-0789c4c9851d"),
                            Rating = 3m,
                            UserId = new Guid("022b41a2-7e40-4104-98a9-7cd8dcc67a0f")
                        },
                        new
                        {
                            Id = new Guid("69a1439b-b6bc-4f47-9a12-705bea3cfcb5"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(180), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("ead5e981-2125-47a6-a0a6-b4d6ffa14339"),
                            Rating = 4.5m,
                            UserId = new Guid("022b41a2-7e40-4104-98a9-7cd8dcc67a0f")
                        },
                        new
                        {
                            Id = new Guid("2e5ca995-a048-46aa-b075-e8a7afc2af2b"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(185), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("b839d79d-a339-416d-ade0-936edbcf6691"),
                            Rating = 9.5m,
                            UserId = new Guid("022b41a2-7e40-4104-98a9-7cd8dcc67a0f")
                        },
                        new
                        {
                            Id = new Guid("41a2a170-777d-437c-8792-b027313b9e73"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(185), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("ca2a8812-e099-495f-b036-06accb4355a7"),
                            Rating = 2m,
                            UserId = new Guid("db08b3be-859a-4012-914f-4bb4f5aad27c")
                        },
                        new
                        {
                            Id = new Guid("637677af-90e0-4ed0-9256-4c39d0c17151"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(190), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("37498bd4-d693-4ce0-933c-6cc8f9377ae9"),
                            Rating = 7m,
                            UserId = new Guid("db08b3be-859a-4012-914f-4bb4f5aad27c")
                        },
                        new
                        {
                            Id = new Guid("e5ccfdce-d8e1-4fd0-943b-f57f5fefbc0b"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(194), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("dc6b3d4d-959b-4cef-a7eb-f92731811b95"),
                            Rating = 7.5m,
                            UserId = new Guid("db08b3be-859a-4012-914f-4bb4f5aad27c")
                        },
                        new
                        {
                            Id = new Guid("e4f614b9-466a-4519-a60f-5a08c517e963"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(194), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("81aa0a92-70fb-4ffc-860b-a81ca47be098"),
                            Rating = 5m,
                            UserId = new Guid("db08b3be-859a-4012-914f-4bb4f5aad27c")
                        },
                        new
                        {
                            Id = new Guid("9e7450af-4e1e-4e4b-bd85-a8272d644d27"),
                            DateSet = new DateTimeOffset(new DateTime(2019, 3, 23, 22, 29, 27, 482, DateTimeKind.Unspecified).AddTicks(199), new TimeSpan(0, 0, 0, 0, 0)),
                            MovieId = new Guid("f7b47d60-3232-426d-a1aa-833aef7bb676"),
                            Rating = 6m,
                            UserId = new Guid("db08b3be-859a-4012-914f-4bb4f5aad27c")
                        });
                });

            modelBuilder.Entity("MoviesApi.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTimeOffset>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d61bd5e-d9b3-4eda-822c-d7ce257abbc2"),
                            DateOfBirth = new DateTimeOffset(new DateTime(2001, 3, 23, 22, 29, 27, 466, DateTimeKind.Unspecified).AddTicks(1721), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tom",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("86e4da8a-6ea9-416a-af9b-c037249c8f3c"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1947, 3, 23, 22, 29, 27, 466, DateTimeKind.Unspecified).AddTicks(2568), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Jamal",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = new Guid("b18a8a2d-0369-48a4-8ca8-8af187487594"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1991, 3, 23, 22, 29, 27, 466, DateTimeKind.Unspecified).AddTicks(2577), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "John",
                            LastName = "Robertson"
                        },
                        new
                        {
                            Id = new Guid("022b41a2-7e40-4104-98a9-7cd8dcc67a0f"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1973, 3, 23, 22, 29, 27, 466, DateTimeKind.Unspecified).AddTicks(2582), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Leon",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("db08b3be-859a-4012-914f-4bb4f5aad27c"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1987, 3, 23, 22, 29, 27, 466, DateTimeKind.Unspecified).AddTicks(2582), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Katie",
                            LastName = "McDonald"
                        });
                });

            modelBuilder.Entity("MoviesApi.Data.Entities.RatingEntity", b =>
                {
                    b.HasOne("MoviesApi.Data.Entities.MovieEntity", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK_Movies_Ratings")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviesApi.Data.Entities.UserEntity", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Users_Ratings")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
